syntax on
set mouse=a
set number
colorscheme dracula
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set hlsearch

"set nocompatible
"filetype off

map <C-n> :NERDTreeToggle<CR>
map <C-Right> :bnext<cr>
map <C-Left> :bprev<cr>

let NERDTreeMapOpenInTab='\r'
let g:bufferline_echo = 1

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Plugin 'othree/html5.vim'
Plugin 'townk/vim-autoclose'
Plugin 'docunext/closetag.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'bling/vim-bufferline'
Plugin 'dracula/vim'
